### ISSUE TITLE
Question on Gaps

### ISSUE THREAD

**Issue by HolterPhylo** [McGill-CSB/PHYLO#49]
I have a difficult time understanding how gaps are sometimes created when there are no gaps in any of the chains on screen.

Could you direct me to where can I read on these gaps and how they happen in the tree like here?

![Phylo Gaps2 2012-12-16_165813](https://f.cloud.github.com/assets/3037251/16018/fd059ba4-47f5-11e2-882e-c1176db8e485.jpg)

In this image, a gap is generated for the 3rd black box  from the top of the tree.   Why is it not blue like both the 1st and 2nd black boxes of the tree at that position?

Are there colors that dominate others?

Thanks for your help.

**Comment by waldispuhl** [comment]
Looks like there's a bug here. Do you know the level id ?

**Comment by HolterPhylo** [comment]
This ID# 32.

The gap is not there with only the first 4 chains.  It is there after...

**Comment by HolterPhylo** [comment]
Still would appreciate answers to questions...

**Comment by waldispuhl** [comment]
We're looking into this actually. the ancestor in your screenshot is wrong so we must trace the source of the bug. We'll keep you updated ASAP.

**Comment by HolterPhylo** [comment]
Another Gap bug example?  Puzzle ID# 10.

Here one gap accounted for at the bottom but none is showing when viewing any of the tree black boxes.

Hope it helps solve the problem.

![Phylo ID10 1 gap 2012-12-21_145241](https://f.cloud.github.com/assets/3037251/27820/6d958d56-4ba8-11e2-86be-1f076552a3b6.jpg)

**Comment by waldispuhl** [comment]
So I checked our algorithms and everything seems ok. Your examples illustrate well some features of the algorithm we are using to compute ancestors. We are using a customized version of the Fitch algorithm: http://phylo.cs.mcgill.ca/eng/faq.html#scoring Compared to the original algorithm, we treat gaps as a fifth type of blocks (fifth color) but with a lower priority. Importantly all columns are treated independently.  It may not always calculate the best ancestors but in practice it's fast and accurate enough for our needs.
Here are some (incomplete but hopefully useful) justifications of the configurations you observed.
In Puzzle #32, you display the ancestor at the root of the tree. The gap is the only common "color" between the first 7 sequences and the last one. So now you may want to ask, why other surrounding blocks in the ancestor are not gaps as well? Well, it turns out that there's an unfortunate configuration for us in that column… For instance, we would like to have a violet block instead of a gap… Our variant of the Fitch algorithm cannot remember at the level of the root that a violet block was present in the first sequence. It has been erased when we choose to assign a blue block as the ancestor of the first triplet (human, mouse,bat). Try to move the rightmost violet block in the 4th sequence in that column to see that the gap disappeared. you can also simulate the algorithm as explained in the link above to see why a gap has been selected in this particular column.
In fact, this example illustrates well the limitation of our scoring scheme. But we estimate (and have tested!) that this algorithm approximate well enough better scoring algorithm. 
Puzzle #10 is easier. The gap has a lower priority that the blue block. Therefore, the blue block is immediately selected.
I hope it helps. I realize that we are still missing a good documentation of our variant of Fitch. I'll try to post one on the website ASAP.
Thanks for these useful examples!
