### ISSUE TITLE
Question on Ancestors/Scoring

### ISSUE THREAD

**Issue by Equixor** [McGill-CSB/PHYLO#60]
I've noticed some odd behavior with the ancestors, and thus some odd scoring behavior. Below is an example of what I was seeing.

![image](https://f.cloud.github.com/assets/952317/35003/a82ef2d4-5177-11e2-8777-b48247ceccd8.png)

![image](https://f.cloud.github.com/assets/952317/35004/af17fc58-5177-11e2-9c2f-e9bae25288a3.png)

Then Stage 3 is added and I've moved it off to the end and noticed a strange score drop. When I looked at the same ancestor, I saw this:

![image](https://f.cloud.github.com/assets/952317/35006/e4b5da2e-5177-11e2-9bfd-b975f38bc713.png)

![image](https://f.cloud.github.com/assets/952317/35007/eb739d74-5177-11e2-8684-70f2547cd3d9.png)

A gap appeared in the ancestor, which then causes a gap which then drops the score. If I move it one to  left:

![image](https://f.cloud.github.com/assets/952317/35008/69fab95c-5178-11e2-92c4-992efeec826c.png)

![image](https://f.cloud.github.com/assets/952317/35009/749daf86-5178-11e2-89ae-dad36eea7576.png)

You can see the gap closed and the ancestor got shorter.

This leads to some pretty wild score differences when blocks are pushed off to the side like in this case. Is this expected behavior? and if so why was the ancestor of Stage 2 affected by Stage 3?

**Comment by waldispuhl** [comment]
You're raising a very interesting point that illustrate some specificities and directions to improve of Phylo.
The ancestors are calculated with a variant of the Fitch algorithm (http://phylo.cs.mcgill.ca/eng/faq.html#scoring)
This algorithm works in two passes. A bottom-up phase (from leaves of the tree to the root) and a top-down (from the root to the specie leaves). When you add a 4th sequence to your previous configuration with 3 seqs (1st and 2nd screenshots), new information coming for the 4th sequence add new constraints to the choice of ancestors for the root of the 3 initial species/leaves. In that particular case, the gap is the only common "color" available at the root for the tree with 3 seqs and the new 4th seq. Thus, we choose it at this position.

The ancestors are suposed to be calculated such that the final score evaluated after all pairwise comparisons is optimal. However, the algorithm we use is not always optimal. Sometimes, ancestor calculations such as the one you showed here are sub-optimal. In that particular case, this is due to the fact that the ancestors are calculated independently for each column. Hence, we ignore the context (left & right) and this sometimes results in sub-optimal ancestor assignments.

The truth is that calculating the best ancestor is a difficult problem that may took too much time to provide an immediate scoring. We found that the algorithm we use is fast, relatively easy to explain (http://phylo.cs.mcgill.ca/eng/faq.html#scoring) and accurate enough in most of the cases.

We tried to address this limitation in the expert version: http://phylo.cs.mcgill.ca/expert/
With that program you can edit the ancestors directly on the nodes and improve the ancestor calculation when our algorithm does not return the best result.

We had a similar discussion with @HolterPhylo in issue #49 . Maybe some information there can complete this answer.

I do realize that more details should be provided on ancestor calculation for advanced players and I'll try to complete the tutorial ASAP. Meanwhile, feel free to post or email me any question you may have.

I hope it helps!

**Comment by Equixor** [comment]
Thanks,

I've been working through Fitch and have read through the comments on issue #49. Below is my take from it written out. Feel free to use any/all in the documentation you're putting together regarding your modified Fitch.

So in my example the column after the Purple - Orange - Orange at the end of the first row would result in this tree: (forgive the text based tree drawing, W = White, O = Orange)

<pre>
       {W}
     /     \
   W        {W,O}
          /       \
        W          {O}
                 /     \
               O         O
</pre>

Therefore the resulting ancestor block is White instead of Orange due to treating empty as the 5th block color.

In the case of Holter's puzzle 32 example...
![fd059ba4-47f5-11e2-882e-c1176db8e485 1 ](https://f.cloud.github.com/assets/952317/36346/9ab5ac5a-5317-11e2-8b4f-d75de368913c.jpg)

<pre>
      {W}
   /        \
W     {P, O, G, W, B}
    /               \
  {P, O, G}           {B, W}
    /      \          /      \
 G         {P,O}     W       {B}
          /     \           /   \
         O      P          B     {P, B}
                                /     \
                               P       B
</pre>

---

---

---

Now that that drawing is done, I'm curious why White was used as a 5th color instead of Null like in the original algorithm. Both of the above examples are translated using the original Fitch algorithm below (my understanding of it at least):

For the top example:

<pre>
       {O}
     /     \
   ∅        {O}
          /       \
        ∅         {O}
                 /     \
               O         O
</pre>

and for Holter's

<pre>
  {P, O, G, B}
   /        \
∅         {P, O, G, B}
         /              \
  {P, O, G}             {B}
    /      \           /    \
 G         {P,O}     ∅     {B}
          /     \          /   \
         O      P         B    {P, B}
                              /     \
                             P       B
</pre>

At least for these 2 cases it seems that the original algorithm would give superior results due to the cost of a gap opening up.

**Comment by waldispuhl** [comment]
Thanks for your careful analysis. Your figures are helpful to explain what is going on and I will probably try to post them on the website (I'm considering creating a discussion page with best contributions and explanations such as yours for other users)
Unless I misunderstand your question about white & Null, I think the answer is that the original Fitch does not handle gaps. Thus we just modified it and added a 5th color representing gaps (or Null). The main point in your demonstration is to discuss the way we treat gaps during the 1st step of the algorithm: Should we consider gaps as a 5th color and in that case we add them to the sets of internal nodes, or as empty sets which implies that they will not appear in the sets of possible ancestors associated to the internal nodes.  
I agree that in the case above the second option is better. Although, I'm not sure yet (or at least I need to think more about it) it'll always be the case (but I may be wrong). Mainly because gaps will appear in ancestors only if all leaves in the subtree are also gaps. I'm not discarding this option and in fact I'm willing to look at this variant more closely as it may results in better scoring. Recently, we were more focused on the way to handle trailing gaps, but I think your observation is interesting and need to be tested (we need to know if in average it produces better results than the current algorithm). We will keep you updated here of upcoming tests.
Thanks again!

**Comment by Equixor** [comment]
Thanks,

Let me know if there's anything I can do to help things out. I can likely throw together a c# based Phylo program that can graphically compare the two algorithms side by side for a given set and show the scores accordingly.

**Comment by waldispuhl** [comment]
That would be interesting. Another option could be compute the score with both methods on the puzzles stored in our database and look which scheme ends up with the best ranking (as given by advanced scoring methods).

**Comment by Equixor** [comment]
I've tried to review the 2011 results so that I could write a parser that could be used to compare the different algorithms but I can't figure out how the data stores the tree information in the maf files.

**Comment by waldispuhl** [comment]
Actually the full tree we're using is this one:
(((((((((((((((((hg19:0.006591,panTro2:0.006639):0.002184,gorGor1:0.009411):0.009942,ponAbe2:0.018342):0.014256,(rheMac2:0.036199,papHam1:0.04):0.021496):0.01,calJac1:0.066389):0.056911,tarSyr1:0.135169):0.011307,(micMur1:0.091452,otoGar1:0.128984):0.035463):0.015304,tupBel1:0.183583):0.004688,(((((mm9:0.083220,rn4:0.090564):0.196605,dipOrd1:0.209532):0.022555,cavPor3:0.223415):0.009828,speTri1:0.146894):0.025042,(oryCun2:0.116009,ochPri2:0.198295):0.100037):0.015355):0.020666,(((vicPac1:0.105252,(turTru1:0.064182,bosTau4:0.121911):0.025111):0.039691,((equCab2:0.107726,(felCat3:0.097971,canFam2:0.100888):0.049486):0.006252,(myoLuc1:0.141155,pteVam1:0.111787):0.033187):0.004179):0.011699,(eriEur1:0.220580,sorAra1:0.266859):0.056117):0.021065):0.023276,(((loxAfr3:0.083775,proCap1:0.152633):0.026190,echTel1:0.240221):0.049905,(dasNov2:0.115179,choHof1:0.096272):0.052373):0.006713):0.132748,(monDom5:0.325899,macEug1:0.3):0.1):0.072430,ornAna1:0.453916):0.109903,((galGal3:0.166386,taeGut1:0.170717):0.199763,anoCar1:0.509545):0.108130):0.166150,xenTro2:0.852482):0.300396,(((tetNig2:0.224774,fr2:0.205294):0.191836,(gasAcu1:0.313967,oryLat2:0.478451):0.058404):0.322824,danRer6:0.731166):0.155214):0.511293,petMar1:0.511293)

Then you must extract the subtree corresponding to the species. The number after the semi-colon is the branch length.  We use it to re-calculate the scores before re-insertion but for the scoring scheme used in the game you can just ignore it. If needed, I may have python scripts to parse that.

**Comment by andreengels** [comment]
I'm having a problem with the solution in the expert game: If I change the ancestor(s) somewhere, and then make another change somewhere completely different in the genome, the ancestor(s) go back to the calculated version. Also, if one reverts to a best or saved solution, it will go to that solution with the computer-calculated ancestors. It would be good to lock the ancestors, or at least lock whether they are empty or another value.

**Comment by waldispuhl** [comment]
Thanks for pointing this problem. We'll work on it this week and have that fixed ASAP.
