### ISSUE TITLE
Need more puzzles!

### ISSUE THREAD

**Issue by Durdge** [McGill-CSB/PHYLO#74]
In advanced phylo, it appears that all of the puzzles have been solved at least twice.  While I may be able to improve on the existing solutions a little bit, I would love to have the option of trying untouched puzzles.  Perhaps I'm not grasping the science side of this app, but it seems like there should be an extremely large number of puzzles that would be useful to have available.

**Comment by waldispuhl** [comment]
There is indeed. So far we limited the number of puzzle in order to make a good estimate of the performance of the system. We will soon (1 week or 2) add more puzzles for further testing. Also the current ones can still be optimized. We're working on it and will announce new puzzles here and on our twitter account.

**Comment by Durdge** [comment]
Been a while since I've played, but just invited a bunch of folks to play.  If you have the new puzzles, you might close this "ticket".

**Comment by Durdge** [comment]
Whoops, didn't mean to close it...

**Comment by waldispuhl** [comment]
Thanks for sharing!! We just added new puzzles related to obesity. We'll keep adding puzzles in upcoming days/weeks.
